version: "3.0"

services:
  elasticsearch:
    image: elasticsearch:7.17.9
    container_name: elasticsearch
    environment:
      - node.name=single-node
      - cluster.name=backtony
      - discovery.type=single-node
    ports:
      - 9200:9200
    networks:
      - es-bridge

  kibana:
    container_name: kibana
    image: kibana:7.17.9
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - es-bridge
  logstash:
    image: logstash:7.17.9
    container_name: logstash
    environment: 
      - xpack.monitoring.enabled=false
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./config-dir:/config-dir
    command: logstash -f /config-dir/logstash.conf

networks:
  es-bridge:
    driver: bridge

