spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ncs?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.data.elasticsearch.client.WIRE: TRACE
